### ISSUE TITLE
On `initialize` and `terminate`

### ISSUE THREAD

**Issue by klingtnet** [musitdev/portmidi-rs#22]
In my opinion it would be more *rusty* to provide a trait object with something like `PortMidi::new()` which implements [`Drop`](https://doc.rust-lang.org/std/ops/trait.Drop.html) and calls `portmidi::terminate` when dropped. Both `initalize` as well as `terminate` should not be part of the public interface.

**Comment by klingtnet** [comment]
There are additional things that I would like to change, some of them would break the API. If I find some spare time this week to implement those changes, then I will open or more additional PRs or if you don't like the changes, fork the project.

**Comment by musitdev** [comment]
Do it if you have time. I don't think it's a problem to change the API. Your change seems logic. I'll integrated them when they are done.

**Comment by klingtnet** [comment]
:+1:

**Comment by klingtnet** [comment]
Ideas: we should use [`midi-rs`](https://github.com/samdoshi/midi-rs) to decode the message on-the-fly, or give the user the possibility to get a raw message. In most cases you want a decoded message.

**Comment by musitdev** [comment]
I've made a test with midi-rs and it's missing some function to convert midi message to midi-rs and the opposite. If you're motivated to do them, it will be a good improvement to use midi with rust.
My second thought is how to integrate it, in new crate, in portmidi with a dependence to midi.rs or in midi.rs??? No answer yet.

**Comment by klingtnet** [comment]
Good question, I would vote for using midi.rs as dependency in portmidi-rs or midi.rs (which is the newer one?).

**Comment by samdoshi** [comment]
Hi guys, so I wrote the midi crate back when I was more interested in rust. Haven't got so much time for it at the moment.

At the time I'd also been thinking about trying to output a higher level [message](https://github.com/samdoshi/midi-rs/blob/master/src/message.rs), from what I recall, it's very hard to go from Raw to Message for all the different types of synths out there (e.g. a Waldorf Blofeld will use CC 98-101 for synthesis parameters rather than for [N]RPN). Instead you'd have to give some way for the user to configure the conversion.

More pressing is issue #16, as it stands you can't send or read SysEx as it requires writing and reading 4 byte messages, `MidiMessage` can be tricked into sending 3 bytes padded with a zero to 4, but not 4 proper bytes. Portmidi itself is built around 4 byte messages (or int32s) for it's API, but (I think) internally it uses single bytes and does weird padding to make it fit.

**Comment by klingtnet** [comment]
@samdoshi 
Hi!
You're mentioning a good point, the midi message interpretation differs from manufacturer to manufacturer. We shouldn't get too specific, but we should support at least the types that are mentioned in the [official summary](https://www.midi.org/specifications/item/table-1-summary-of-midi-message) (`midi.org` got a new website :tada:). If this doesn't fit, one could also get a `raw` midi message (the 4 byte struct) and do the interpretation oneself. Providing basic SysEx support should not be too complicated, too. Nevertheless, only a small number of user would need SysEx support, that's why I wouldn't prioritize it. Those who need it are also more likely be programmers themself :smile:

**Comment by musitdev** [comment]
I think that the simpler is to add conversion function to midi-rs for basic message type. If we can provide a way to extend it it's better but not mandatory. The conversion can be extended latter depending on the need otherwise.

**Comment by klingtnet** [comment]
I'm in the works. The PR should come at the end of this week. I've refactored almost everything, so stay tuned. I should write some additional tests, too.

**Comment by musitdev** [comment]
Ok very good.
