### ISSUE TITLE
Implement Send trait for pm::InputPort and pm::OutputPort

### ISSUE THREAD

**Issue by jonas-k** [musitdev/portmidi-rs#23]
When trying to use portmidi in a multithreaded environment, for example to implement a callback functionality, it is not possible to launch a thread and moving something into that thread that contains an InputPort or OutputPort. The error is: the trait `core::marker::Send` is not implemented for the type `*const libc::c_void`

**Comment by musitdev** [comment]
InputPort or OutputPort can't be sync because the  *const libc::c_void is not thread safe. Rust blocks this to avoid multithread problems. In Rust there are two ways to share resource : Mutex or Channel.
The privileged way is channel. In my code I use a thread that manage all Input and Output and Channels to send or receive midi data. For the Input it's a little more complex because you need a multi receiver channel to share the input midi message to several receiver. 
Otherwise depending on your need, your create your input or output in each thread that need it. You can't share port but if only one thread need to write or read it's enough.

**Comment by jonas-k** [comment]
Thank you for your answer. I tried to use an Arc<Mutex<InputPort>> to share it between threads. Even when I cloned it, i couldn't share it. I will try to use multiple Ports now, one for each thread.

**Comment by jonas-k** [comment]
I wrote Arc(Mutex(InputPort)), but it was changed due to the brackets I used.

**Comment by musitdev** [comment]
Arc Mutex should work I think.  I think you should try to use channel because when you're used to it's more efficient and avoid a lot of concurrent problems.
